// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhezhlnivhtfapqkdvqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoZXpobG5pdmh0ZmFwcWtkdnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NzczNjksImV4cCI6MjA1NDM1MzM2OX0.QeJr_g7yeCaDaGH87ZAm226UdnRMN-8QMbntaUwqiFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);